{% set name = "fa2_modified" %}
{% set version = "0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 13aae915d666ba5f897ea890705f2d0100987915a605e0ae503c817dd55e0451

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - cython
    - setuptools
    - pip
    - python
  run:
    - numpy
    - python
    - scipy
    - tqdm

test:
  imports:
    - fa2_modified
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AminAlam/fa2_modified
  summary: 'The fastest ForceAtlas2 algorithm for Python (and NetworkX)'
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://pypi.org/project/fa2-modified
  dev_url: https://github.com/AminAlam/fa2_modified

extra:
  recipe-maintainers:
    - n-elie
