{% set name = "fa2_modified" %}
{% set version = "0.3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f74b1cd001709785bbd89f3dad1fc0237a1a8a54b8c8ce0f8583ef4776e81299

build:
  number: 0
  script:
    # Delete old generated c file so that cython can generate new ones
    # Otherwise, it will be incompatible with python 3.9+
    - rm -f fa2_modified/fa2util.c       # [unix]
    - del /f /q fa2_modified\fa2util.c   # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - cython
    - pip
    - python
  run:
    - numpy
    - python
    - scipy
    - tqdm

test:
  imports:
    - fa2_modified
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AminAlam/fa2_modified
  summary: 'The fastest ForceAtlas2 algorithm for Python (and NetworkX)'
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://pypi.org/project/fa2-modified
  dev_url: https://github.com/AminAlam/fa2_modified

extra:
  recipe-maintainers:
    - n-elie
