{% set name = "fa2_modified" %}
{% set version = "0.3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7751e55fbbddaaf0b3afa25882d90147b6f04d983faf9f07a307bcebb538d69b

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - cython
    - pip
    - python
  run:
    - numpy
    - python
    - scipy
    - tqdm

test:
  imports:
    - fa2_modified
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AminAlam/fa2_modified
  summary: 'The fastest ForceAtlas2 algorithm for Python (and NetworkX)'
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://pypi.org/project/fa2-modified
  dev_url: https://github.com/AminAlam/fa2_modified

extra:
  recipe-maintainers:
    - n-elie
